package com.example.todoappkotlin.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF0F766E)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFCCFBF1)
val LightOnPrimaryContainer = Color(0xFF042F2E)
val LightSecondary = Color(0xFF334155)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE2E8F0)
val LightOnSecondaryContainer = Color(0xFF0F172A)
val LightTertiary = Color(0xFFF97316)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFEDD5)
val LightOnTertiaryContainer = Color(0xFF7C2D12)
val LightBackground = Color(0xFFF8FAFC)
val LightOnBackground = Color(0xFF0F172A)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF0F172A)
val LightSurfaceVariant = Color(0xFFE2E8F0)
val LightOnSurfaceVariant = Color(0xFF475569)
val LightOutline = Color(0xFFCBD5E1)
val LightOutlineVariant = Color(0xFFE2E8F0)

val DarkPrimary = Color(0xFF5EEAD4)
val DarkOnPrimary = Color(0xFF042F2E)
val DarkPrimaryContainer = Color(0xFF134E4A)
val DarkOnPrimaryContainer = Color(0xFFCCFBF1)
val DarkSecondary = Color(0xFF94A3B8)
val DarkOnSecondary = Color(0xFF0F172A)
val DarkSecondaryContainer = Color(0xFF1E293B)
val DarkOnSecondaryContainer = Color(0xFFE2E8F0)
val DarkTertiary = Color(0xFFFBBF24)
val DarkOnTertiary = Color(0xFF451A03)
val DarkTertiaryContainer = Color(0xFF92400E)
val DarkOnTertiaryContainer = Color(0xFFFFEDD5)
val DarkBackground = Color(0xFF0B1120)
val DarkOnBackground = Color(0xFFE2E8F0)
val DarkSurface = Color(0xFF111827)
val DarkOnSurface = Color(0xFFE2E8F0)
val DarkSurfaceVariant = Color(0xFF1F2937)
val DarkOnSurfaceVariant = Color(0xFF94A3B8)
val DarkOutline = Color(0xFF334155)
val DarkOutlineVariant = Color(0xFF1F2937)

val AppError = Color(0xFFDC2626)
val AppOnError = Color(0xFFFFFFFF)
val AppErrorContainer = Color(0xFFFEE2E2)
val AppOnErrorContainer = Color(0xFF7F1D1D)
